### 新添加商品
POST http://{{host}}:{{port}}/{{context}}/accounts
Content-Type: application/json
Accept: application/json

{
  "description": "工资卡"
}

###
GET http://{{host}}:{{port}}/{{context}}/accounts
Accept: application/json

###
PUT http://{{host}}:{{port}}/{{context}}/accounts/find-by-desc
Content-Type: application/json
Accept: application/json

{
  "description": "工资卡"
}


###
GET http://{{host}}:{{port}}/{{context}}/accounts/batch-append-desc
Accept: application/json
Content-Type: application/json

{
  "description": "-幸运账户"
}
