CREATE TABLE IF NOT EXISTS  account(id BIGINT IDENTITY PRIMARY KEY,description VARCHAR(100), open_time TIMESTAMP);

CREATE TABLE IF NOT EXISTS  product(id BIGINT PRIMARY KEY,name VARCHAR(100), quantity INTEGER );

CREATE TABLE IF NOT EXISTS Lego_Set (id INTEGER, name VARCHAR(100), min_Age INTEGER, max_Age INTEGER);
CREATE TABLE IF NOT EXISTS Handbuch (handbuch_id BIGINT, author VARCHAR(100), text CLOB);
CREATE TABLE IF NOT EXISTS Model (name VARCHAR(100), description CLOB, lego_set INTEGER);
