CREATE TABLE IF NOT EXISTS  account(id BIGINT IDENTITY PRIMARY KEY,description VARCHAR(100), open_time TIMESTAMP);

CREATE TABLE IF NOT EXISTS  product(id BIGINT PRIMARY KEY,name VARCHAR(100), quantity INTEGER );
